In [3]:
import numpy as np

In [4]:
##Q1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

arr = np.arange(2,14).reshape(4,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [5]:
#2). Write code to replace the odd numbers by -1 in the array created by using 
#random.randint( 1 , 50,20) 

arr1 = np.random.randint(1,50,20)
arr1 = np.where(arr1 %2!= 0,-1, arr1)
arr1


array([20,  8, -1, 48, -1, 26,  6, 10, 38, -1, -1, -1, -1, 46, 36, -1, -1,
       -1, 30, -1], dtype=int32)

In [6]:
#Q3A) Perform the following operations on an array of mobile phones prices 6999, 7500, 
#11999, 27899, 14999, 9999.
#Create a 1d-array of mobile phones prices 

m_prices= np.array([6999,7500,11999,14999,9999])
m_prices


array([ 6999,  7500, 11999, 14999,  9999])

In [7]:
# 3B)  Convert this array to float type 
m_prices.astype(float)


array([ 6999.,  7500., 11999., 14999.,  9999.])

In [8]:
# 3C) Append a new mobile having price of 13999 Rs. to this array 
m_prices = np.append(m_prices ,13999)
m_prices

array([ 6999,  7500, 11999, 14999,  9999, 13999])

In [9]:
#3D)  Reverse this array of mobile phones prices 
m_prices[::-1]



array([13999,  9999, 14999, 11999,  7500,  6999])

In [10]:
#3E) Apply GST of 18% on mobile phones prices and update this array. 
m_price = m_prices*0.18
m_price

array([1259.82, 1350.  , 2159.82, 2699.82, 1799.82, 2519.82])

In [11]:
# 3F) Sort the array in descending order of price 
np.sort(m_price)[::-1]


array([2699.82, 2519.82, 2159.82, 1799.82, 1350.  , 1259.82])

In [12]:
# 3G) What is the average mobile phone price 
np.mean(m_price)

np.float64(1964.8499999999997)

In [13]:
# 3H) What is the difference b/w maximum and minimum price 
m_price = np.max(m_price)-np.min(m_price)
m_price


np.float64(1439.9999999999998)

In [16]:
# Q4) Find out the indices of non zero element in given array  
# [1,2,0,0,4,0] 
arr2 = np.array([1,0,2,2,4,0,0,0,0,4])
index = np.nonzero(arr2)
index

(array([0, 2, 3, 4, 9]),)