In [2]:
import numpy as np

In [3]:
#Q1)  Create a NumPy array containing integers from 0 to 9. 

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Q2) Create a NumPy array from a given Python list [10, 20, 30, 40, 50]. 
list = [10,20,30,40,50]
arr1 = np.array(list)
arr1

array([10, 20, 30, 40, 50])

In [5]:
# Q3)Create a 2D array (3x3) with values ranging from 0 to 8. 
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# Q4) . Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 
#1 and 100, and print the shape and size. 
arr2.size

9

In [7]:
arr2.shape

(3, 3)

In [8]:
arr3 = np.random.randint(1,101 ,size= (4,5))
arr3

array([[43, 20, 12, 59, 49],
       [73, 16, 79, 72, 48],
       [41, 82, 37, 39, 42],
       [16,  1, 37, 75, 77]], dtype=int32)

In [9]:
# Q5A) 5. Create a 3x3 array of integers and access: 
# The second element of the first row. 
arr4 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
arr4

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr4[0,1] # it gives 2nd element of 1st row

np.int64(20)

In [24]:
#Q5B) The third column of the 2nd row. 
arr4[1,2]

np.int64(60)

In [25]:
#Q5c) A subarray with the first two rows and last two columns. 
arr4[0:2,-2:]

array([[20, 30],
       [50, 60]])

In [13]:
# Q6)6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array. 
arr5 = np.arange(1,13).reshape(3,4)
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
# 7) . Reshape a 3x3 matrix into a 1D array. 
arr5 = np.array([[1,2,3],
                [5,6,7],
                [8,9,10]])
# np.ravel(arr5)
arr5.reshape(-1)


array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [29]:
# 8) Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, 
#subtraction, multiplication, and division on them. 

arr6 = np.array([[1,2,3],
        [4,5,6]])

arr7 = np.array([[7,8,9],
        [10,11,12]])
arr6+arr7
arr6 -arr7
arr6 *arr7
arr6/arr7





array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [41]:
# 9) Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a 
#given array.




In [46]:
arr8 = np.array([1,2,3,4,5,6])
arr8.mean()
arr8.sum()
arr8.std()

np.float64(1.707825127659933)

In [54]:
# Q10). Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or 
#the @ operator. 

A = np.array([[1,2],
              [4,5]])

B = np.array([[7,8],
              [10,11]])
np.dot(A,B)




array([[27, 30],
       [78, 87]])

In [55]:
A@B

array([[27, 30],
       [78, 87]])

In [65]:
# Q11) Find the transpose of matrix A and matrix B. 
A.T

array([[1, 4],
       [2, 5]])

In [66]:
B.T

array([[ 7, 10],
       [ 8, 11]])

In [63]:
# Q12 ) Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. 
#Explain how broadcasting works in this operation.
array1 = np.array([1,2,3])
array2 = np.array(np.arange(1,10)).reshape(3,3)
array2 +array1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [69]:
#Q13.) Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the 
#entire array.
arr10 = np.array(np.random.randint(1,100, size=(4,4)))
arr10                 

array([[84, 21, 60, 77],
       [49, 91, 58, 59],
       [34, 46, 87,  9],
       [28, 35, 69, 65]], dtype=int32)

In [72]:
arr10.max()



np.int32(91)

In [73]:
arr10.min()

np.int32(9)

In [74]:
arr10.mean()

np.float64(54.5)

In [75]:
# Q14)  Find the row-wise and column-wise sums. 

np.sum(arr10, axis= 0)

array([195, 193, 274, 210])

In [76]:
np.sum(arr10, axis = 1)

array([242, 257, 176, 197])

In [78]:
# Q15. Generate an array of 10 random integers between 1 and 50. 
arr11 = np.array(np.random.randint(1,50,10))
arr11

array([28, 12, 48, 33, 20, 16, 47, 34, 32, 43], dtype=int32)

In [81]:
# Q16)  Generate a 5x5 matrix of random floats between 0 and 1. 
ar12 = np.array(np.linspace(0,1,25)).reshape(5,5)
ar12

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])