In [1]:
import numpy as np 

##  (BASICS)=====PRACTICE QUESTIONS

In [2]:
# Q1)Create a NumPy array from a Python list.

#Q2)Find the shape, size, and datatype of an array.

#Q3)Create an array of zeros, ones, and identity matrix.

#Q4)Generate numbers from 1 to 50 using NumPy.

#Q5)Reshape a 1D array into a 2D array.

#Q6)Find max, min, mean, and sum of an array.

#7)Perform element-wise addition, subtraction, multiplication.

In [3]:
# Q1)Create a NumPy array from a Python list.

arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [4]:
#Q2)Find the shape, size, and datatype of an array.

arr1.shape

(5,)

In [5]:
arr1.size

5

In [7]:
arr1.dtype

dtype('int64')

In [13]:
#Q3)Create an array of zeros, ones, and identity matrix.
arr2 = np.zeros(3)
arr2

array([0., 0., 0.])

In [15]:
arr2 = np.ones(3)
arr2

array([1., 1., 1.])

In [17]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#Q4)Generate numbers from 1 to 50 using NumPy.
arr2 = np.arange(1,51)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [21]:
#Q5)Reshape a 1D array into a 2D array.
arr2.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [22]:
#Q6)Find max, min, mean, and sum of an array.
arr2.sum()

np.int64(1275)

In [23]:
arr2.mean()

np.float64(25.5)

In [24]:
arr2.min()

np.int64(1)

In [25]:
arr2.max()

np.int64(50)

In [28]:
#7)Perform element-wise addition, subtraction, multiplication.
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([11,12,13,14,15,16,17,18,19,20])
arr3 = arr1 +arr2 
arr3

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

# (Medium) === LEVEL QUESTIONS 

In [29]:
#Slice a 2D array (select specific rows and columns).

#Replace all odd numbers in an array with -1.

#Find unique elements and their counts.

#Sort an array along rows and columns.

#Stack two arrays vertically and horizontally.

#Use boolean indexing to filter values > 50.

#Generate random numbers and set a seed.

In [38]:
# Q1) Slice a 2D array (select specific rows and columns).

arr1 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,1,2,3]])
arr1[[0,1,2]]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [40]:
#Q2)Replace all odd numbers in an array with -1.
# new_arr = np.where(arr1 %2 != 0 -1, arr1)
# new_arr

In [42]:
#Find unique elements and their counts.
