In [1]:
import numpy as np


## Array creation  in numpy

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10]) ## using np

In [5]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr1 = np.arange(1,11) ## using arange

In [11]:
arr1

numpy.ndarray

In [13]:
arr1 = np.random.randint(1,100, 10) # using random it ganarates 10 randon numbers between 1 to 100

In [14]:
arr1

array([89, 54, 63, 26, 33, 98, 19, 68, 27, 41], dtype=int32)

In [17]:
arr1 = np.random.rand(10) # using rand it genarte random float values between 0 to 1

In [18]:
arr1

array([0.97158443, 0.51521789, 0.70127638, 0.654287  , 0.2285244 ,
       0.43573974, 0.07120307, 0.83639104, 0.34950484, 0.619878  ])

In [19]:
arr1 = np.zeros(10)   #it genarates 10 float zeros  

In [20]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
arr1 = np.ones(10)# it ganerates 10 float 1

# Check size and itemsize of array 

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1.size

10

In [24]:
arr1.itemsize

8

# How array faster than list

In [29]:
%%time

li1 = [i for i in range(1,1000)]
li2 = [i for i in range(2001, 3000)]
li3 = []
for i in range(0, len(li1)):
    li3.append(li1[i]+li2[i])

CPU times: total: 0 ns
Wall time: 391 μs


In [30]:
%%time
arr1 = np.array(li1)
arr2 = np.array(li2)
arr3 = arr1+arr2

CPU times: total: 0 ns
Wall time: 481 μs


# how array reuire less memory as compare to list 

In [31]:
import sys

In [35]:
li = [10,20,30,40]
sys.getsizeof([0]*len(li))

88

In [33]:
arr1 = np.array([10,20,30,40])
arr1.size*arr1.itemsize

32

# multidimentional array

In [36]:
arr1 = np.array([[1,2,3,4],  # 2D array
                [5,6,7,8],
                [8,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8, 10, 11, 12]])

# to find shape and reshape array

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr1.shape

(6,)

In [38]:
arr2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr2.shape # it gives 3,4 means 3 rows and 4 columns 

(3, 4)

In [41]:
arr3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9],
                [1,2,3]]])
arr3.shape # it gives 1,2,3,1 means no.of 2D array 4 rows and 3 colums 

(1, 4, 3)

In [42]:
arr4 = np.array([[[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [1,2,3]]]])
arr4.shape

(1, 1, 4, 3)

# reshape array

In [43]:
arr1 = np.arange(1,11).reshape(2,5) # it reshape the array 2 rows and 5 columns()2D

In [45]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
arr1 = np.arange(1,16).reshape(1,3,5) # it gives 3*3 matrix (3 rows 5 colums )() 3D

In [47]:
arr1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [48]:
arr1 = np.arange(1,17).reshape(2,2,4)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [49]:
arr1 = np.arange(1,11).reshape(1,1,5,2) #ot gives 4*4 matrix ( 2 columns 5 rows ) 4D
arr1

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]]])

In [51]:
arr1 = np.zeros(10).reshape(1,1,5,2) # 2 colums 5 rows with 0 values
arr1

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [52]:
arr1 = np.ones(27).reshape(3,3,3) # 3blocks 3 rows 3 colums
arr1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
arr1 = np.linspace(1,10,5) #is used to generate evenly spaced numbers between a start and an end values
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [56]:
arr1 = np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attributes

# 1.) ndim = it check dimention of array

In [57]:
arr1 = np.array([1,2,3,4,5,6]) # 1D array
arr1.ndim

1

In [58]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2.ndim

2

In [60]:
arr3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
arr3.ndim

3

# 2) dtype = it checks datatype of elements of array

In [62]:
arr1 = np.array([1,2,3,4])
arr1.dtype

dtype('int64')

In [64]:
arr2 = np.array(['ab','c','def']) # U means unicode string and 3 means maximum lenth of string array here def lenght is 3 therefore u3
arr2.dtype 

dtype('<U3')

In [65]:
arr3 = np.array([1.1,1.2,1.3])
arr3.dtype

dtype('float64')

In [67]:
arr4 = np.array([1,1.2,'abc','c']) # it convert int into float bcz float can store int but int cant store decimal
arr4

array(['1', '1.2', 'abc', 'c'], dtype='<U32')

#  vectorization means it performs operation on each element of array to make the code faster , it not require loops

In [68]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
arr3 = arr1+arr2
arr3

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [70]:
arr1 = np.array([[1,2,3,4], #it add each element of arr1 with each elemnt of arr2
                [4,5,6,7],
                [1,2,3,4]])
arr2 = np.array([5,6,7,8])
arr3 = arr1+arr2
arr3

array([[ 6,  8, 10, 12],
       [ 9, 11, 13, 15],
       [ 6,  8, 10, 12]])

 # Pad  : it is used to add zeros at starting or ending of array

In [72]:
arr1 = np.array([1,2,3,4]) # it adds 4 zeros at starting and 4 zeros at ending
np.pad(arr1,4)

array([0, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0, 0])

In [73]:
arr1 = np.array([1,2,3,4]) # kit adds 4 zeros at ending
np.pad(arr1,(0,4))

array([1, 2, 3, 4, 0, 0, 0, 0])

In [74]:
arr1 = np.array([1,2,3,4])
np.pad(arr1,(1,4)) # it adds 1 zero at beginning and 4 zeros at ending (give staring and ending values )

array([0, 1, 2, 3, 4, 0, 0, 0, 0])

In [76]:
arr1 = np.array([1,2,3,4]) #it add 4 zero at beginning and 1 zero at end
np.pad(arr1,(3,1),constant_values=(4,6))   #we can change default value from 0 to other numbers using constant_values so we add 3 four at start and 1 six at end


array([4, 4, 4, 1, 2, 3, 4, 6])

In [77]:
arr1 = np.array([1,2,3,4]) # it add 4 six at the end and staring value we give 0 therefore it not add at first
np.pad(arr1,(0,4),constant_values=(4,6))


array([1, 2, 3, 4, 6, 6, 6, 6])

# astype : it change the datatype of array elements into another datatype

In [79]:
arr1 = np.array([1,2,3,4,5]) # it changes the array element into the float
arr1.astype(float)

array([1., 2., 3., 4., 5.])

In [81]:
arr1.astype(str) # it converts into string

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [82]:
arr1.astype(int) # it converts into int

array([1, 2, 3, 4, 5])

# Mathematical Functions

In [84]:
arr1 = np.array([1,2,3,4,5,6,1,2,3,4,5,7,8,2]) # sum of array
arr1.sum()

np.int64(53)

In [85]:
arr1.mean()

np.float64(3.7857142857142856)

In [86]:
arr1.max()

np.int64(8)

In [87]:
arr1.min()

np.int64(1)

In [88]:
arr1.std() # standard deviation it calculates how much data is spared out

np.float64(2.1104695289563082)

In [89]:
arr1.argmax() # it give the index of maximum element from array here maximum elemet is 8 so its index is 12

np.int64(12)

In [91]:
np.sqrt(arr1) # it findes square root of each elements of array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.64575131, 2.82842712, 1.41421356])

In [4]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 1.4 MB/s eta 0:00:06
   -- ------------------------------------- 0.5/8.0 MB 1.4 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/8.0 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.0 MB 1.1 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.0 MB 1.1 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.0 MB 1.1 MB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.0 MB 966.7 kB/s eta 0:00:07
   ------- -------------------------------- 1.6/8.0 MB 966.7 kB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.0 MB 1.0 MB/s eta 0:00:06
   ----------- ---------------------------- 2.4/8.0 MB 1.1 MB/s eta 0:00:06
   ------------- ---